### ISSUE TITLE
10 coeurs sur les classes "Guerrier" et "Soutien"

### ISSUE THREAD

**Issue by ArcaniiX** [Synchroneyes/MineralContest#9]
Bonsoir à vous,

Après avoir testé la version 2.8.4.5 de votre plugin, j'ai remarqué que les 5 coeurs qui devaient être enlevé sur les classes "Guerrier" et "Soutien" ne l'étaient pas et la vie restait à 10 coeurs toute la partie.

Par ailleurs, petit message pour féliciter le travail effectué car les possibilités et le gameplay apportés grâce au plugin est excellent, et la possibilité de le paramétrer un maximum me fascine également.
Seul point à modifier pour une meilleure approche pour les débutants serait le site des commandes ( https://mc.monvoisin-kevin.fr/commandes ) qui ne répertorie pas toutes les commandes disponibles, même si je souligne l'effort ainsi que la possibilité d'avoir un aperçu des settings en écrivant la commande sans modifier les valeurs en jeu.

Ainsi je termine ce message pour demander comment modifier/ajouter les kits que vous avez mit à disposition, car mes amis et moi voudrions des kits différents de ceux proposés ou juste modifier certaines de leurs fonctionnalités.

**Comment by Synchroneyes** [comment]
Hello, merci pour le commentaire. Je règle ce soucis dès que j'ai un peu de dispo.
Concernant les kits, ils se situent ici: https://github.com/Synchroneyes/MineralContest/tree/master/src/main/java/fr/synchroneyes/mineral/Kits

Pour ajouter un nouveau kit, il suffit d'étendre la classe KitAbstract, puis de l'ajouter dans le KitManager https://github.com/Synchroneyes/MineralContest/blob/4a01a8a1c6053bd69ca51bc13410794d3b2e3b4f/src/main/java/fr/synchroneyes/mineral/Kits/KitManager.java#L83

Pour modifier un kit, il suffit de modifier la classe correspondante au kit à modifier, puis build le tout
